### ISSUE TITLE
what result do we need to do downstream analysis

### ISSUE THREAD

**Issue by yx-xu** [YeoLab/merge_peaks#1]
Hi!
   I have a question during i use merge_peaks to normalize peak called by CLIPper. There are several steps in example of merge_peaks, but which result do we need to do downstream analysis? Or, which peak file could be considered as confident result of a RBP binding sites?
   Looking forward for your reply! Thank you very much!

**Comment by byee4** [comment]
Hi, 

Please see the readme for full descriptions, but generally you can define the peak file outputs with this option:

```
### FINAL OUTPUTS
merged_peaks_custombed: 204.01v02.IDR.out.0102merged.bed
merged_peaks_bed: 204.01v02.IDR.out.0102merged.custombed
```

For inputs to the pipeline, the actual fields are defined in the README, but if you're using the eCLIP analysis pipeline, let me attach the extensions that correspond to these inputs: 

PCR-deduped sorted BAM file from your IP dataset (same one that you provide Clipper)
`myRBP.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam
`

PCR-deduped sorted BAM file from your size-matched INPUT dataset
`myRBP.INPUT.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam
`

Clipper-called peak clusters (or input-normalized 
`myRBP.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.peakClusters.bed`

**Comment by yx-xu** [comment]
Okay, Thanks for your reply!  And after we normalize the peak with input,  what peaks we think as enriched? I use the criteria p<0.05 and FC>=2, what  criteria do you suggest? Thank you again!

**Comment by byee4** [comment]
The ENCODE integrated paper uses the following cutoffs of -log10(p) >= 3 and log2(fold) >= 3. This merge_peaks pipeline scripts has these values by default [here](https://github.com/YeoLab/merge_peaks/blob/master/bin/perl/parse_idr_peaks.pl). 

[Link to paper](https://www.nature.com/articles/s41586-020-2077-3)

**Comment by yx-xu** [comment]
HI!
    I used the cutoffs of -log10(p) >= 3 and log2(fold) >= 3, but there are only several peaks passed, so I relaxed the criterial. I don't know if it is feasible to do so. 
   You helped me a lot! Thank  you very much!
