### ISSUE TITLE
IDR analysis error

### ISSUE THREAD

**Issue by zhangjun-123** [YeoLab/merge_peaks#2]
Hi ,dear yeolab ,i'm doing the IDR analysis following your eclip-seq processing pipeline V2.2 ,i got the following error 

"**Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: HTTPConnectionPool(host='schema.org', port=80): Max retries exceeded with url: /docs/schema_org_rdfa.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca02ae0130>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
../cwl/samtools-index.cwl:54:3: Warning: Field `class` contains undefined reference to
                                `http://schema.org/CreativeWork` "
../cwl/samtools-index.cwl:69:7: Warning: checking item
                                Warning:   Field `class` contains undefined reference to
                                `http://schema.org/Organization`
../cwl/samtools-index.cwl:65:5: Warning: checking item
                                Warning:   Field `class` contains undefined reference to
                                `http://schema.org/Organization`
../cwl/samtools-index.cwl:59:3: Warning: Field `class` contains undefined reference to
                                `http://schema.org/Person`**

i donot know what's wrong with it ,can you help me? Thank you very much!

**Comment by byee4** [comment]
Not an error - these warnings have to do with a cwl tool we've been using that has optional metadata described but not fully implemented in our pipeline yet.

**Comment by zhangjun-123** [comment]
So,what should i do to perform the IDR analysis following your pipeline ? Or this step is not working in the pipeline ? Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeoLab/merge_peaks"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 晚上11:53
收件人:&nbsp;"YeoLab/merge_peaks"<merge_peaks@noreply.github.com&gt;;
抄送:&nbsp;"内含子寻外显子"<1138976957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YeoLab/merge_peaks] IDR analysis error (#2)





 
Not an error - these warnings have to do with a cwl tool we've been using that has optional metadata described but not fully implemented in our pipeline yet.

**Comment by byee4** [comment]
It should work!
