### ISSUE TITLE
Which file do I use as the result?

### ISSUE THREAD

**Issue by hxdde** [YeoLab/merge_peaks#4]
In the result, there are mainly *.idr.out, *.idr.out.normed.bed and *.custombed files.  According to Supplementary Protocol 2: eCLIP-seq Processing Pipeline, the *.custombed file should be the final result and contain individual replicate information. However, in the Readme, file *.custombed is told that it cannot be used. So in which file should I use the results to annotate genes? If I can get a reply, I would be extremely grateful.

**Comment by byee4** [comment]
The custombed files should have the same information as what's in the paper, so they can be used. However since BED is a more acceptable standard, we recommend using that as a "final" result.
